src/AppBundle/Entity/Enduser.php
<?php

namespace AppBundle\Entity;

use AppBundle\Entity\CloudFile;
use Doctrine\DBAL\Types\TextType;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\Validator\Constraints as SecurityAssert;


/**
 * Enduser
 *
 * @ORM\Table(name="enduser")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\EnduserRepository")
 * @UniqueEntity(fields="mail", message="Girmiş olduğunuz email kullanılmaktadır.")
 * @UniqueEntity(fields="username", message="Girmiş olduğunuz kullanıcı adı kullanılmaktadır.")
 */
class Enduser implements   UserInterface, \Serializable
{



    public function __construct()
    {
        $this->files = new ArrayCollection();

        $preferences=array('sharing_enabled'=>true,'sharing_notification_enabled'=>true,'api_enabled'=>false);
        $this->setPreferences($preferences);
        $this->setLastLoggedIn(new \DateTime('now'));

    }


    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     *
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     * @Assert\Length(min="2",minMessage="En az 1 karakter girmelisiniz.")
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="username", type="string", length=255, unique=true)
     *
     */
    private $username;

    /**
     * @var string
     * @ORM\Column(name="password", type="string", length=255)
     */
    private $password;


    /**
     * @var string
     * @ORM\Column(name="mail", type="string", unique=true , nullable=false )
     */


    private $mail;



    /**
     * @var \DateTime
     *
     * @ORM\Column(name="lastLoggedIn", type="datetime", nullable=true)
     */
    private $lastLoggedIn;


    /**
     *
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\CloudFile", mappedBy="user")
     */
    private $files;

    /**
     *
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\BatchDownloadRequest", mappedBy="owner")
     */
    private $batchFiles;


    /**
     *
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\SharedCloudFile", mappedBy="owner")
     *
     */
    private $shareOwners;



    /**
     *
     *
     * @ORM\Column(name="sex", type="boolean")
     */
    private $sex;


    /**
     *
     * @var string
     * @ORM\Column(name="city", type="text")
     */
    private $city;


    /**
     * @var array
     *
     * @ORM\Column(name="preferences", type="json_array")
     */
    private $preferences;

    /**
     *
     * @var string
     * @ORM\Column(name="maiden_name", type="text", nullable=true)
     *
     */
    private $maidenName;

    /**
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\SharedCloudFile", mappedBy="target")
     */
    private $shareTargets;


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Enduser
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set username
     *
     * @param string $username
     *
     * @return Enduser
     */
    public function setUsername($username)
    {
        $this->username = $username;

        return $this;
    }

    /**
     * Get username
     *
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Set password
     *
     * @param string $password
     *
     * @return Enduser
     */
    public function setPassword($password)
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Get password
     *
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Set password
     *
     * @param string $password
     *
     * @return Enduser
     */
    public function setNewPassword($password)
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Get password
     *
     * @return string
     */
    public function getNewPassword()
    {
        return $this->password;
    }


    /**
     * Set mail
     *
     * @param string $mail
     *
     * @return Enduser
     */
    public function setMail($mail)
    {
        $this->mail = $mail;

        return $this;
    }

    /**
     * Get mail
     *
     * @return string
     */
    public function getMail()
    {
        return $this->mail;
    }





    /**
     * Set lastLoggedIn
     *
     * @param \DateTime $lastLoggedIn
     *
     * @return Enduser
     */
    public function setLastLoggedIn($lastLoggedIn)
    {
        $this->lastLoggedIn = $lastLoggedIn;

        return $this;
    }

    /**
     * Get lastLoggedIn
     *
     * @return \DateTime
     */
    public function getLastLoggedIn()
    {
        return $this->lastLoggedIn;
    }


    public function getSalt()
    {
        // you *may* need a real salt depending on your encoder
        // see section on salt below
        return null;
    }



    public function getRoles()
    {
        return array('ROLE_USER');
    }

    public function eraseCredentials()
    {
    }

    /** @see \Serializable::serialize() */
    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->username,
            $this->mail,
            $this->password,
            // see section on salt below
            // $this->salt,
        ));
    }

    /** @see \Serializable::unserialize() */
    public function unserialize($serialized)
    {
        list (
            $this->id,
            $this->username,
            $this->mail,
            $this->password,
            // see section on salt below
            // $this->salt
            ) = unserialize($serialized);
    }

    /**
     * Add file
     *
     * @param \AppBundle\Entity\CloudFile $file
     *
     * @return Enduser
     */
    public function addFile(\AppBundle\Entity\CloudFile $file)
    {
        $this->files[] = $file;

        return $this;
    }

    /**
     * Remove file
     *
     * @param \AppBundle\Entity\CloudFile $file
     */
    public function removeFile(\AppBundle\Entity\CloudFile $file)
    {
        $this->files->removeElement($file);
    }

    /**
     * Get files
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getFiles()
    {
        return $this->files;
    }

    /**
     * Add shareOwner
     *
     * @param \AppBundle\Entity\SharedCloudFile $shareOwner
     *
     * @return Enduser
     */
    public function addShareOwner(\AppBundle\Entity\SharedCloudFile $shareOwner)
    {
        $this->shareOwners[] = $shareOwner;

        return $this;
    }

    /**
     * Remove shareOwner
     *
     * @param \AppBundle\Entity\SharedCloudFile $shareOwner
     */
    public function removeShareOwner(\AppBundle\Entity\SharedCloudFile $shareOwner)
    {
        $this->shareOwners->removeElement($shareOwner);
    }

    /**
     * Get shareOwners
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getShareOwners()
    {
        return $this->shareOwners;
    }

    /**
     * Add shareTarget
     *
     * @param \AppBundle\Entity\SharedCloudFile $shareTarget
     *
     * @return Enduser
     */
    public function addShareTarget(\AppBundle\Entity\SharedCloudFile $shareTarget)
    {
        $this->shareTargets[] = $shareTarget;

        return $this;
    }

    /**
     * Remove shareTarget
     *
     * @param \AppBundle\Entity\SharedCloudFile $shareTarget
     */
    public function removeShareTarget(\AppBundle\Entity\SharedCloudFile $shareTarget)
    {
        $this->shareTargets->removeElement($shareTarget);
    }

    /**
     * Get shareTargets
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getShareTargets()
    {
        return $this->shareTargets;
    }

    /**
     * Add batchFile
     *
     * @param \AppBundle\Entity\BatchDownloadRequest $batchFile
     *
     * @return Enduser
     */
    public function addBatchFile(\AppBundle\Entity\BatchDownloadRequest $batchFile)
    {
        $this->batchFiles[] = $batchFile;

        return $this;
    }

    /**
     * Remove batchFile
     *
     * @param \AppBundle\Entity\BatchDownloadRequest $batchFile
     */
    public function removeBatchFile(\AppBundle\Entity\BatchDownloadRequest $batchFile)
    {
        $this->batchFiles->removeElement($batchFile);
    }

    /**
     * Get batchFiles
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getBatchFiles()
    {
        return $this->batchFiles;
    }

    /**
     * Set sex
     *
     * @param string $sex
     *
     * @return Enduser
     */
    public function setSex($sex)
    {
        $this->sex = $sex;

        return $this;
    }

    /**
     * Get sex
     *
     * @return boolean
     */
    public function getSex()
    {
        return $this->sex;
    }

    /**
     * Set city
     *
     * @param string $city
     *
     * @return Enduser
     */
    public function setCity($city)
    {
        $this->city = $city;

        return $this;
    }

    /**
     * Get city
     *
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }


    /**
     * Set $preferences
     *
     * @param array $preferences
     *
     * @return Enduser
     */
    public function setPreferences($preferences)
    {

src/AppBundle/Resources/views/user/changepass.html.twig
{% extends 'AppBundle::base.html.twig' %}

{% block body %}
    {{ form_start(form, {'attr': {'action': path('change_pass')}}) }}
    {{ form_row(form.password) }}
    {{ form_row(form.newPassword) }}
        <input class="btn btn-primary" type="submit" value="Şifreyi Değiştir">
    {{ form_end(form) }}
{% endblock %}

src/AppBundle/Resources/views/user/forgetpass.html.twig
{% extends 'AppBundle::base.html.twig' %}

{% block body %}
    {% for flash_message in app.session.flashbag.get('notice') %}
        <div class="alert alert-danger alert-dismissable">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            {{ flash_message }}
        </div>
    {% endfor %}
{{ form_start(form) }}
{{ form_label(form.mail) }}
{{ form_widget(form.mail) }}

{{ form_label(form.username) }}
{{ form_widget(form.username) }}
 <input class="btn btn-primary" type="submit" value="İleri">
{{ form_end(form) }}
{% endblock %}

src/AppBundle/Resources/views/user/index.html.twig
{% extends 'AppBundle::base.html.twig' %}

{% block body %}
    {% if is_granted('ROLE_USER') %}



    {% else %}
        {% if error %}
            <div>{{ error.messageKey|trans(error.messageData, 'security') }}</div>
        {% endif %}
        {% for flash_message in app.session.flashbag.get('notice') %}
            <div class="alert alert-danger alert-dismissable">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{ flash_message }}
            </div>
        {% endfor %}
        {{ form_start(form) }}

        {{ form_errors(form) }}
        {{ form_row(form.username) }}
        {{ form_row(form.password) }}

        <input class="btn btn-primary" type="submit" value="Giris">
        <a class="btn btn-success" href="{{ path('register') }}">Yeni Kullanıcı</a>
        <a class="btn btn-warning" href="{{ path('forget_pass') }}">Şifremi Unuttum</a>

        {{ form_end(form) }}


    {% endif %}
{% endblock %}

{% block stylesheets %}
    <style>

    </style>
{% endblock %}

src/AppBundle/Resources/views/user/register.html.twig
{% extends 'AppBundle::base.html.twig' %}

{% block body %}

<a class="btn btn-info" href="{{ path('user_index') }}">Kullanıcı Girişine Geri Dön</a>
    <hr>
{{ form_start(register, {'attr': {'action': path('register'),'novalidate':'novalidate'}}) }}
    {{ form_label(register.name)  }}
    {{ form_widget(register.name) }}
    <b>{{ form_errors(register.name,{'attr': {'class':'text-danger'}}) }}</b>


    {{ form_label(register.username) }}
    {{ form_widget(register.username)}}
    <b>{{ form_errors(register.username)}}</b>

    {{ form_label(register.mail)  }}
    {{ form_widget(register.mail) }}
    <b>{{ form_errors(register.mail) }}</b>

    {{ form_row(register.password) }}
    <b>{{ form_errors(register.password) }}</b>


    {{ form_row(register.city)   }}




    {{ form_row(register.city,{'attr': {'id':'city'}}) }}

    {{ form_label(register.sex) }}
    {{ form_widget(register.sex) }}
    <b> {{ form_errors(register.sex) }}</b>

    {{ form_label(register.maidenName) }}
    {{ form_widget(register.maidenName) }}
    <b> {{ form_errors(register.maidenName) }}</b>



    <input type="submit" class="btn btn-primary" value="Kaydı Tamamla">
{{ form_end(register) }}


{% endblock %}

src/AppBundle/Resources/views/user/settings.html.twig
{% extends 'AppBundle::base.html.twig' %}

{% block body %}

    <div class="container">
    <div class="row">
{{ form_start(form) }}
    <div class="col-md-10">
        <div class="panel panel-default">
            <div class="panel-heading">Ayarlar</div>
                <div class="panel-body">
                    <h4><b>Paylaşım Ayarları</b></h4>
                    <ul class="list-group">
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-md-6">{{ form_label(form.sharing_enabled) }}</div>
                                <div class="col-md-6">{{ form_widget(form.sharing_enabled) }}</div>
                            </div>
                        </li>
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-md-6">{{ form_label(form.sharing_notification) }}</div>
                                <div class="col-md-6">{{ form_widget(form.sharing_notification) }}</div>
                            </div>
                        </li>
                    </ul>
                    <h4><b>API Ayarları</b></h4>
                    <div class="list-group">
                    <li class="list-group-item">
                        <div class="row">
                            <div class="col-md-6">{{ form_label(form.api_enabled) }}</div>
                            <div class="col-md-6">{{ form_widget(form.api_enabled) }}</div>
                        </div>
                    </li>
                    </ul>
                    </div>
                </div>
            <div class="panel-footer container-fluid">
               <input type="submit" class="btn btn-primary pull-right">
            </div>
        </div>
    </div>
{{ form_end(form) }}
{% endblock %}